# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Felipe Nipo
email: fpnipo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  12+ years experience as Software Engineer with a post-graduate degree, experience in backend development with exposure to distributed systems, event sourcing, and event-driven architectures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fnipo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: felipenipo
github_username:  fnipo
repository: "fnipo/fnipo.github.io"

# Build settings
#theme: minima
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-spaceship

safe: true
sass:
  quiet_deps: true  # Suppress deprecation warnings that come from dependencies. Disable to debug building issues.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



# --- Minimal-mistakes config ---
minimal_mistakes_skin: "default"

# font:
#   body: "Inter, sans-serif"
#   heading: "Inter, sans-serif"

locale: "en"

#logo: "/assets/images/88x88.png"
masthead_title: "Felipe Nipo"
# site.description: ""  # for SEO
# url: "https://mademistakes.com"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      classes: wide

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      share: true
      show_date: false
      read_time: true

atom_feed:
  hide: true

search: true

lunr:
  search_within_pages: true

og_image: /assets/bio-photo.jpg

social:
  links:
    - "https://twitter.com/felipenipo"
    - "https://www.linkedin.com/in/felipenipo/"

author:
  name: "Felipe Nipo"
  avatar: "/assets/bio-photo.jpg"
  bio: "Software Engineer" # note: Markdown is allowed
  location: "Dublin, Ireland"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/felipenipo"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/felipenipo/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fnipo"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-P9LR4DJVN7"
    anonymize_ip: false # default